### ISSUE TITLE
Official fraud

### ISSUE THREAD

**Issue by kksal55** [JackSiro/Q2A-PM-Adapter-Plugin#1]
Why don't you mention it as a premium plugin? I learn after I add. Shame!!

**Comment by JacksiroKe** [comment]
No I think it's a shame to you to expect everything to be free.

**Comment by kksal55** [comment]
I did not say why you are distributing paid. This is your choice.
You have to mention that a software is paid. You are deceiving people.

**Comment by JacksiroKe** [comment]
I published this plugin for the first time in 2018 and people have been paying for it but here you come in 2021 to say such. I find this intresting

**Comment by kksal55** [comment]
You don't want to understand me. I say that you should indicate that it is a premium add-on in the description section. I'm not asking you why it's premium. You mislead people.
